version: '3.0'

services:
  nginx:
    container_name: nginx
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - server
  server:
    container_name: server
    restart: always
    build: server
    ports:
      - "3000:3000"
    links:
      - mongo-db-server
  mongo-db-server:
    container_name: mongo-db-server
    image: mongo
    ports:
      - "27017:27017"
